[package]
name = "cita-database"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
cita-logger = "0.1.0"
rocksdb = "0.12.2"

[dev-dependencies]
